development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: sample_app_DEVELOPMENT
  pool: 5
  username: postgres
  password: sonkong15
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: sample_app_TEST
  pool: 5
  username: postgres
  password: sonkong15
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  pool: 5
  username: postgres
  password: 